export const askAI = async (prompt: string, context: any = null): Promise<string> => {
  try {
    const res = await fetch("/api/ai", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({ prompt, context })
    });

    if (!res.ok) {
      const errText = await res.text();
      return `❌ Server AI Error (${res.status}): ${errText || "Unable to retrieve response from backend AI service."}`;
    }

    const data = await res.json();
    return data?.text || "No response generated by backend AI assistant.";
  } catch (e: any) {
    console.error("askAI error:", e);
    return `❌ Request failed: ${e?.message || String(e)}`;
  }
};
